services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
    tty: true
    env_file: .env
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
